GET http://127.0.0.1:5000/movies/
Accept: application/json

###

GET http://127.0.0.1:5000/movies/?director_id=12
Accept: application/json

###

GET http://127.0.0.1:5000/movies/?genre_id=4
Accept: application/json

###

GET http://127.0.0.1:5000/movies/?year=2010
Accept: application/json

###

GET http://127.0.0.1:5000/directors/
Accept: application/json

###

GET http://127.0.0.1:5000/directors/1
Accept: application/json

###

GET http://127.0.0.1:5000/genres/
Accept: application/json

###

GET http://127.0.0.1:5000/genres/1
Accept: application/json

###

GET http://127.0.0.1:5000/movies/21
Accept: application/json

###

POST http://127.0.0.1:5000/movies/
Accept: application/json
Content-Type: application/json

{
  "title": "Жанна Д'Арк",
  "trailer": "https://www.youtube.com/watch?v=ISdH6Ye5mgw",
  "year": 1999,
  "rating": 9,
  "description": "Толпа жарит француженку в центре города."
}

###

PUT http://127.0.0.1:5000/movies/21
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "This title is updated",

}

###

PATCH http://127.0.0.1:5000/movies/3
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "The New Title",
  "trailer": "Updated trailer",
  "year": 31,
  "rating": 2,
  "description": "This movie data was updated",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:5000/movies/21
